export const _CONFIG = {
	DISCORD_APP_ID: '',
	DISCORD_SERVER_ID: '',
	DISCORD_TOKEN: '',
	DISCORD_INVITE_LINK: '',
	DISCORD_CITIZEN_ID: '',
	DISCORD_ADMIN_ID: '',
	DISCORD_MOD_ID: '',
	DISCORD_SUPPORTER_ID: '',
	DISCORD_STATUS_CHANNEL: '',
	DISCORD_PREFIX: '+',
	LANGUAGE: 'de',
	WHITELIST: true
};