import * as alt from "alt";
import * as native from 'natives';
import { EnableIpl, getInteriorByType, SetIplProp, getConfig } from 'mr-functions';
import { Start } from './unload.mjs';
import { Gun_Yacht } from './gunyacht.mjs';
import { Yacht } from './yacht.mjs';
import { Bunkers } from './bunkers.mjs';
import { Graffitis } from './graffitis.mjs';
import { BahamaMamas } from './bahamamamas.mjs';
import { Ufos } from './ufos.mjs';
import { redCarpet } from './redcarpet.mjs';
import { northYankton } from './northyankton.mjs';
import { heistCarrier } from './heistcarrier.mjs';
import { cayoPerico } from './cayoperico.mjs';
import { Michael } from './michael.mjs';
import { Simeon } from './simeon.mjs';
import { Franklin } from './franklin.mjs';
import { FranklinAunt } from './franklinaunt.mjs';
import { Floyd } from './floyd.mjs';
import { TrevorsTrailer } from './trevorstrailer.mjs';
import { ZancudoGates } from './zancudogates.mjs';
import { LesterFactory } from './lesterfactory.mjs';
import { StripClub } from './stripclub.mjs';
import { Ammunations } from './ammunations.mjs';
import { Nightclub } from './nightclub.mjs';
import { BikerClubhouse1 } from './bikerclubhouse1.mjs';
import { BikerClubhouse2 } from './bikerclubhouse2.mjs';
import { Counterfeit } from './counterfeit.mjs';
import { Cocaine } from './cocaine.mjs';
import { BikerDocumentForgery } from './document.mjs';
import { BikerMethLab } from './meth.mjs';
import { BikerWeedFarm } from './weed.mjs';
import { DoomsdayFacility } from './facility.mjs';
import { ExecutiveApartment1 } from './apartment1.mjs';
import { ExecutiveApartment2 } from './apartment2.mjs'; 
import { ExecutiveApartment3 } from './apartment3.mjs';
import { HighLifeApartment1 } from './apartment4.mjs';
import { HighLifeApartment2 } from './apartment5.mjs';
import { HighLifeApartment3 } from './apartment6.mjs';
import { HighLifeApartment4 } from './apartment7.mjs';
import { HighLifeApartment5 } from './apartment8.mjs';
import { HighLifeApartment6 } from './apartment9.mjs';
import { HighEndApartment1 } from './apartment10.mjs';
import { HighEndApartment2 } from './apartment11.mjs';
import { LowEndHouse } from './house1.mjs';
import { MidEndHouse } from './house2.mjs';
import { HighEndHouse1 } from './house3.mjs';
import { HighEndHouse2 } from './house4.mjs';
import { HighEndHouse3 } from './house5.mjs';
import { HighEndHouse4 } from './house6.mjs';
import { HighEndHouse5 } from './house7.mjs';
import { HighEndHouse6 } from './house8.mjs';
import { HighEndHouse7 } from './house9.mjs';
import { HighEndHouse8 } from './house10.mjs';
import { FinanceOffice1 } from './office1.mjs';
import { FinanceOffice2 } from './office2.mjs';
import { FinanceOffice3 } from './office3.mjs';
import { FinanceOffice4 } from './office4.mjs';
import { Garage1 } from './garage1.mjs';
import { Garage2 } from './garage2.mjs';
import { Garage3 } from './garage3.mjs';
import { Garage4 } from './garage4.mjs';
import { Blips } from './blips.mjs';
Start.Unload();
alt.requestIpl("post_hiest_unload");
alt.requestIpl("refit_unload");
alt.requestIpl("FINBANK");
alt.requestIpl("Coroner_Int_on");
alt.requestIpl("coronertrash");
alt.requestIpl("CS1_02_cf_onmission1");
alt.requestIpl("CS1_02_cf_onmission2");
alt.requestIpl("CS1_02_cf_onmission3");
alt.requestIpl("CS1_02_cf_onmission4");
alt.requestIpl("farm");
alt.requestIpl("farmint");
alt.requestIpl("farm_lod");
alt.requestIpl("farm_props");
alt.requestIpl("des_farmhouse");
alt.requestIpl("FIBlobby");
alt.requestIpl("atriumglmission");
alt.requestIpl('dt1_05_hc_end');
alt.requestIpl('dt1_05_hc_req');
alt.requestIpl('dt1_05_hc_remove');
alt.requestIpl("FruitBB");
alt.requestIpl("sc1_01_newbill");
alt.requestIpl("hw1_02_newbill");
alt.requestIpl("hw1_emissive_newbill");
alt.requestIpl("sc1_14_newbill");
alt.requestIpl("dt1_17_newbill");
alt.requestIpl("id2_14_during_door");
alt.requestIpl("id2_14_during1");
alt.requestIpl("facelobby");
alt.requestIpl("v_tunnel_hole");
alt.requestIpl("Carwash_with_spinners");
alt.requestIpl("sp1_10_real_interior");
alt.requestIpl("sp1_10_real_interior_lod");
alt.requestIpl("ch1_02_open");
alt.requestIpl("bkr_bi_id1_23_door");
alt.requestIpl("lr_cs6_08_grave_closed");
alt.requestIpl("methtrailer_grp1");
alt.requestIpl("bkr_bi_hw1_13_int");
alt.requestIpl("CanyonRvrShallow");
alt.requestIpl("bh1_47_joshhse_unburnt");
alt.requestIpl("bh1_47_joshhse_unburnt_lod");
alt.requestIpl("hei_sm_16_interior_v_bahama_milo_");
alt.requestIpl("cs3_05_water_grp1");
alt.requestIpl("cs3_05_water_grp1_lod");
alt.requestIpl("trv1_trail_start");
alt.requestIpl("canyonriver01");
alt.requestIpl("canyonriver01_lod");
alt.requestIpl("ferris_finale_anim")
alt.requestIpl("rc12b_fixed");
alt.requestIpl("rc12b_hospitalinterior_lod");
alt.requestIpl("rc12b_hospitalinterior");
alt.requestIpl("hei_dlc_windows_casino");
alt.requestIpl("hei_dlc_casino_aircon");
alt.requestIpl("vw_casino_main");
alt.requestIpl("vw_casino_garage");
alt.requestIpl("vw_casino_carpark");
alt.requestIpl("vw_casino_penthouse");
let penthouse = getInteriorByType(976.6364,70.2947,115.1641,"vw_dlc_casino_apart", "vw_casino_penthouse");
let ks_casino_vault = getInteriorByType(946.251,43.2715,58.9172,"ks_casino_vault", "ks_casino_vault_milo_");
let ks_casino_main = getInteriorByType(935.1050,42.5656,71.2737,"ks_casino_main", "ks_casino_main_milo_");
let ks_casino_back = getInteriorByType(974.5600,22.5161,70.8396,"ks_casino_back", "ks_casino_back_milo_");
let ks_casino_tunnel = getInteriorByType(930.1539,-0.2010,59.1323,"ks_casino_tunnel", "ks_casino_tunnel_milo_");
native.activateInteriorEntitySet(penthouse, "set_pent_tint_shell");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_party_1");  
native.activateInteriorEntitySet(penthouse, "set_pent_media_bar_open");
native.activateInteriorEntitySet(penthouse, "set_pent_spa_bar_open");
native.activateInteriorEntitySet(penthouse, "set_pent_dealer");
native.deactivateInteriorEntitySet(penthouse, "set_pent_nodealer");
native.deactivateInteriorEntitySet(penthouse, "set_pent_media_bar_closed");
native.deactivateInteriorEntitySet(penthouse, "set_pent_spa_bar_closed");
native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_01");
native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_03");
native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_02");
native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_04");
native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_05");
native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_06");
native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_07");
native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_08");
native.activateInteriorEntitySet(penthouse, "set_pent_pattern_09");
native.deactivateInteriorEntitySet(penthouse, "set_pent_arcade_modern");
native.activateInteriorEntitySet(penthouse, "set_pent_arcade_retro");
native.activateInteriorEntitySet(penthouse, "set_pent_clutter_03");
native.activateInteriorEntitySet(penthouse, "set_pent_clutter_02");
native.activateInteriorEntitySet(penthouse, "set_pent_clutter_01");
native.deactivateInteriorEntitySet(penthouse, "set_pent_lounge_blocker");
native.deactivateInteriorEntitySet(penthouse, "set_pent_guest_blocker");
native.deactivateInteriorEntitySet(penthouse, "set_pent_office_blocker");
native.deactivateInteriorEntitySet(penthouse, "set_pent_cine_blocker");
native.deactivateInteriorEntitySet(penthouse, "set_pent_spa_blocker");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_blocker");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_party_after");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_clutter");
native.activateInteriorEntitySet(penthouse, "set_pent_bar_party_2");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_light_0");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_light_01");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_light_02");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_party_0");
native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_party_1");
native.setInteriorEntitySetColor(penthouse,"set_pent_tint_shell",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_1",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_tint_shell",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_media_bar_open",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_spa_bar_open",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_dealer",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_nodealer",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_media_bar_closed",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_spa_bar_closed",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_01",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_03",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_02",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_04",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_05",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_06",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_07",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_08",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_09",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_arcade_modern",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_arcade_retro",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_clutter_03",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_clutter_02",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_clutter_01",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_lounge_blocker",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_guest_blocker",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_office_blocker",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_cine_blocker",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_spa_blocker",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_blocker",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_after",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_clutter",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_2",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_light_0",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_light_01",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_light_02",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_0",0);
native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_1",0);
native.refreshInterior(penthouse);
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_diamonds_02");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_diamonds_01");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_gold_02");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_gold_01");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_art_02");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_art_01");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_cash_02");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_cash_01");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_dressing");
native.activateInteriorEntitySet(ks_casino_vault, "set_spawn_group2");
native.activateInteriorEntitySet(ks_casino_vault, "set_spawn_group1");
native.deactivateInteriorEntitySet(ks_casino_vault, "set_vault_door_broken");
native.activateInteriorEntitySet(ks_casino_vault, "set_vault_door");
native.deactivateInteriorEntitySet(ks_casino_vault, "set_vault_door_closed");
native.refreshInterior(ks_casino_vault);
native.activateInteriorEntitySet(ks_casino_main, "casino_manager_default");
native.activateInteriorEntitySet(ks_casino_main, "casino_manager_workout");
native.refreshInterior(ks_casino_main);
native.activateInteriorEntitySet(ks_casino_back, "casino_back_laundry_damage");
native.refreshInterior(ks_casino_back);
native.activateInteriorEntitySet(ks_casino_tunnel, "set_tunnel_collapse");
native.refreshInterior(ks_casino_tunnel);
Graffitis.Enable(getConfig("Load_Graffitis"));
BahamaMamas.Enable(getConfig("Load_Bahamamama"));
Ufos.Enable(getConfig("Load_Ufos"));
redCarpet.Enable(getConfig("Load_redCarpet"));
northYankton.Enable(getConfig("Load_northYankton"));
heistCarrier.Enable(getConfig("Load_heistCarrier"));
cayoPerico.Enable(getConfig("Load_cayoPerico"));
Bunkers.Enable(getConfig("Load_Bunkers"));
Gun_Yacht.Enable(getConfig("Load_Gun_Yacht"));
Yacht.Enable(getConfig("Load_Yacht"));
Michael.Enable(getConfig("Load_Michael"));
Simeon.Enable(getConfig("Load_Simeon"));
Franklin.Enable(getConfig("Load_Franklin"));
FranklinAunt.Enable(getConfig("Load_FranklinAunt"));
Floyd.Enable(getConfig("Load_Floyd"));
TrevorsTrailer.Enable(getConfig("Load_TrevorsTrailer"));
ZancudoGates.Enable(getConfig("Load_ZancudoGates"));
LesterFactory.Enable(getConfig("Load_LesterFactory"));
StripClub.Enable(getConfig("Load_StripClub"));
Ammunations.Enable(getConfig("Load_Ammunations"));
Nightclub.Enable(getConfig("Load_Nightclub"));
BikerClubhouse1.Enable(getConfig("Load_BikerClubhouse1"));
BikerClubhouse2.Enable(getConfig("Load_BikerClubhouse2"));
Counterfeit.Enable(getConfig("Load_Counterfeit"));
Cocaine.Enable(getConfig("Load_Cocaine"));
BikerDocumentForgery.Enable(getConfig("Load_BikerDocumentForgery"));
BikerMethLab.Enable(getConfig("Load_BikerMethLab"));
BikerWeedFarm.Enable(getConfig("Load_BikerWeedFarm"));
DoomsdayFacility.Enable(getConfig("Load_DoomsdayFacility"));
ExecutiveApartment1.Enable(getConfig("Load_ExecutiveApartment1"));
ExecutiveApartment2.Enable(getConfig("Load_ExecutiveApartment2"));
ExecutiveApartment3.Enable(getConfig("Load_ExecutiveApartment3"));
HighLifeApartment1.Enable(getConfig("Load_HighLifeApartment1"));
HighLifeApartment2.Enable(getConfig("Load_HighLifeApartment2"));
HighLifeApartment3.Enable(getConfig("Load_HighLifeApartment3"));
HighLifeApartment4.Enable(getConfig("Load_HighLifeApartment4"));
HighLifeApartment5.Enable(getConfig("Load_HighLifeApartment5"));
HighLifeApartment6.Enable(getConfig("Load_HighLifeApartment6"));
HighEndApartment1.Enable(getConfig("Load_HighEndApartment1"));
HighEndApartment2.Enable(getConfig("Load_HighEndApartment2"));
LowEndHouse.Enable(getConfig("Load_LowEndHouse"));
MidEndHouse.Enable(getConfig("Load_MidEndHouse"));
HighEndHouse1.Enable(getConfig("Load_HighEndHouse1"));
HighEndHouse2.Enable(getConfig("Load_HighEndHouse2"));
HighEndHouse3.Enable(getConfig("Load_HighEndHouse3"));
HighEndHouse4.Enable(getConfig("Load_HighEndHouse4"));
HighEndHouse5.Enable(getConfig("Load_HighEndHouse5"));
HighEndHouse6.Enable(getConfig("Load_HighEndHouse6"));
HighEndHouse7.Enable(getConfig("Load_HighEndHouse7"));
HighEndHouse8.Enable(getConfig("Load_HighEndHouse8"));
FinanceOffice1.Enable(getConfig("Load_FinanceOffice1"));
FinanceOffice2.Enable(getConfig("Load_FinanceOffice2"));
FinanceOffice3.Enable(getConfig("Load_FinanceOffice3"));
FinanceOffice4.Enable(getConfig("Load_FinanceOffice4"));
Garage1.Enable(getConfig("Load_Garage1"));
Blips.Enable(getConfig("IPL_Blip_Loader"));
if (getConfig("Load_cayoPerico")){
	alt.on("connectionComplete", () => {
		if(getConfig("Load_cayoPerico")){
			const blip = new alt.PointBlip(5943.5679611650485, -6272.114833599767, 2);
			blip.alpha = 0;
			alt.everyTick(() => {
				native.setRadarAsExteriorThisFrame();
				native.setRadarAsInteriorThisFrame(alt.hash("h4_fake_islandx"), 4700.0, -5145.0, 0, 0);
				native.setDeepOceanScaler(0.1);
			});
		}
	});
}