import * as alt from "alt";
import * as native from 'natives';
import { EnableIpl, getInteriorByType, SetIplProp, getConfig } from 'mr-functions';
import { Gun_Yacht } from './gunyacht.mjs';
import { Yacht } from './yacht.mjs';
import { Bunkers } from './bunkers.mjs';
import { Graffitis } from './graffitis.mjs';
import { BahamaMamas } from './bahamamamas.mjs';
import { Ufos } from './ufos.mjs';
import { redCarpet } from './redcarpet.mjs';
import { northYankton } from './northyankton.mjs';
import { heistCarrier } from './heistcarrier.mjs';
import { cayoPerico } from './cayoperico.mjs';
import { Michael } from './michael.mjs';
import { Simeon } from './simeon.mjs';
import { Franklin } from './franklin.mjs';
import { FranklinAunt } from './franklinaunt.mjs';
import { Floyd } from './floyd.mjs';
import { TrevorsTrailer } from './trevorstrailer.mjs';
import { ZancudoGates } from './zancudogates.mjs';
import { LesterFactory } from './lesterfactory.mjs';
import { StripClub } from './stripclub.mjs';
import { Ammunations } from './ammunations.mjs';
import { Nightclub } from './nightclub.mjs';
import { BikerClubhouse1 } from './bikerclubhouse1.mjs';
import { BikerClubhouse2 } from './bikerclubhouse2.mjs';
import { Counterfeit } from './counterfeit.mjs';
import { Cocaine } from './cocaine.mjs';
import { BikerDocumentForgery } from './document.mjs';
import { BikerMethLab } from './meth.mjs';
import { BikerWeedFarm } from './weed.mjs';
import { DoomsdayFacility } from './facility.mjs';
import { ExecutiveApartment1 } from './apartment1.mjs';
import { ExecutiveApartment2 } from './apartment2.mjs'; 
import { ExecutiveApartment3 } from './apartment3.mjs';
import { HighLifeApartment1 } from './apartment4.mjs';
import { HighLifeApartment2 } from './apartment5.mjs';
import { HighLifeApartment3 } from './apartment6.mjs';
import { HighLifeApartment4 } from './apartment7.mjs';
import { HighLifeApartment5 } from './apartment8.mjs';
import { HighLifeApartment6 } from './apartment9.mjs';
import { HighEndApartment1 } from './apartment10.mjs';
import { HighEndApartment2 } from './apartment11.mjs';
import { LowEndHouse } from './house1.mjs';
import { MidEndHouse } from './house2.mjs';
import { HighEndHouse1 } from './house3.mjs';
import { HighEndHouse2 } from './house4.mjs';
import { HighEndHouse3 } from './house5.mjs';
import { HighEndHouse4 } from './house6.mjs';
import { HighEndHouse5 } from './house7.mjs';
import { HighEndHouse6 } from './house8.mjs';
import { HighEndHouse7 } from './house9.mjs';
import { HighEndHouse8 } from './house10.mjs';
	alt.requestIpl("post_hiest_unload");
	alt.requestIpl("refit_unload");
	alt.requestIpl("FINBANK");
	alt.requestIpl("Coroner_Int_on");
	alt.requestIpl("coronertrash");
	alt.requestIpl("CS1_02_cf_onmission1");
	alt.requestIpl("CS1_02_cf_onmission2");
	alt.requestIpl("CS1_02_cf_onmission3");
	alt.requestIpl("CS1_02_cf_onmission4");
	alt.requestIpl("farm");
	alt.requestIpl("farmint");
	alt.requestIpl("farm_lod");
	alt.requestIpl("farm_props");
	alt.requestIpl("des_farmhouse");
	alt.requestIpl("FIBlobby");
	alt.requestIpl("atriumglmission");
	alt.requestIpl('dt1_05_hc_end');
	alt.requestIpl('dt1_05_hc_req');
	alt.requestIpl('dt1_05_hc_remove');
	alt.requestIpl("FruitBB");
	alt.requestIpl("sc1_01_newbill");
	alt.requestIpl("hw1_02_newbill");
	alt.requestIpl("hw1_emissive_newbill");
	alt.requestIpl("sc1_14_newbill");
	alt.requestIpl("dt1_17_newbill");
	alt.requestIpl("id2_14_during_door");
	alt.requestIpl("id2_14_during1");
	alt.requestIpl("facelobby");
	alt.requestIpl("v_tunnel_hole");
	alt.requestIpl("Carwash_with_spinners");
	alt.requestIpl("sp1_10_real_interior");
	alt.requestIpl("sp1_10_real_interior_lod");
	alt.requestIpl("ch1_02_open");
	alt.requestIpl("bkr_bi_id1_23_door");
	alt.requestIpl("lr_cs6_08_grave_closed");
	alt.requestIpl("methtrailer_grp1");
	alt.requestIpl("bkr_bi_hw1_13_int");
	alt.requestIpl("CanyonRvrShallow");
	alt.requestIpl("bh1_47_joshhse_unburnt");
	alt.requestIpl("bh1_47_joshhse_unburnt_lod");
	alt.requestIpl("hei_sm_16_interior_v_bahama_milo_");
	alt.requestIpl("cs3_05_water_grp1");
	alt.requestIpl("cs3_05_water_grp1_lod");
	alt.requestIpl("trv1_trail_start");
	alt.requestIpl("canyonriver01");
	alt.requestIpl("canyonriver01_lod");
	alt.requestIpl("ferris_finale_anim")
	alt.requestIpl("rc12b_fixed");
	alt.requestIpl("rc12b_hospitalinterior_lod");
	alt.requestIpl("rc12b_hospitalinterior");
	alt.requestIpl("hei_dlc_windows_casino");
	alt.requestIpl("hei_dlc_casino_aircon");
	alt.requestIpl("vw_casino_main");
	alt.requestIpl("vw_casino_garage");
	alt.requestIpl("vw_casino_carpark");
	alt.requestIpl("vw_casino_penthouse");
	let penthouse = getInteriorByType(976.6364,70.2947,115.1641,"vw_dlc_casino_apart", "vw_casino_penthouse");
	let ks_casino_vault = getInteriorByType(946.251,43.2715,58.9172,"ks_casino_vault", "ks_casino_vault_milo_");
	let ks_casino_main = getInteriorByType(935.1050,42.5656,71.2737,"ks_casino_main", "ks_casino_main_milo_");
	let ks_casino_back = getInteriorByType(974.5600,22.5161,70.8396,"ks_casino_back", "ks_casino_back_milo_");
	let ks_casino_tunnel = getInteriorByType(930.1539,-0.2010,59.1323,"ks_casino_tunnel", "ks_casino_tunnel_milo_");
	native.activateInteriorEntitySet(penthouse, "set_pent_tint_shell");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_party_1");  
	native.activateInteriorEntitySet(penthouse, "set_pent_media_bar_open");
	native.activateInteriorEntitySet(penthouse, "set_pent_spa_bar_open");
	native.activateInteriorEntitySet(penthouse, "set_pent_dealer");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_nodealer");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_media_bar_closed");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_spa_bar_closed");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_01");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_03");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_02");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_04");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_05");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_06");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_07");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_pattern_08");
	native.activateInteriorEntitySet(penthouse, "set_pent_pattern_09");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_arcade_modern");
	native.activateInteriorEntitySet(penthouse, "set_pent_arcade_retro");
	native.activateInteriorEntitySet(penthouse, "set_pent_clutter_03");
	native.activateInteriorEntitySet(penthouse, "set_pent_clutter_02");
	native.activateInteriorEntitySet(penthouse, "set_pent_clutter_01");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_lounge_blocker");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_guest_blocker");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_office_blocker");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_cine_blocker");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_spa_blocker");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_blocker");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_party_after");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_clutter");
	native.activateInteriorEntitySet(penthouse, "set_pent_bar_party_2");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_light_0");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_light_01");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_light_02");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_party_0");
	native.deactivateInteriorEntitySet(penthouse, "set_pent_bar_party_1");
	native.setInteriorEntitySetColor(penthouse,"set_pent_tint_shell",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_1",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_tint_shell",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_media_bar_open",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_spa_bar_open",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_dealer",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_nodealer",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_media_bar_closed",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_spa_bar_closed",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_01",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_03",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_02",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_04",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_05",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_06",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_07",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_08",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_pattern_09",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_arcade_modern",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_arcade_retro",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_clutter_03",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_clutter_02",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_clutter_01",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_lounge_blocker",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_guest_blocker",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_office_blocker",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_cine_blocker",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_spa_blocker",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_blocker",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_after",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_clutter",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_2",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_light_0",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_light_01",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_light_02",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_0",0);
	native.setInteriorEntitySetColor(penthouse, "set_pent_bar_party_1",0);
	native.refreshInterior(penthouse);
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_diamonds_02");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_diamonds_01");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_gold_02");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_gold_01");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_art_02");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_art_01");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_cash_02");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_cash_01");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_dressing");
	native.activateInteriorEntitySet(ks_casino_vault, "set_spawn_group2");
	native.activateInteriorEntitySet(ks_casino_vault, "set_spawn_group1");
	native.deactivateInteriorEntitySet(ks_casino_vault, "set_vault_door_broken");
	native.activateInteriorEntitySet(ks_casino_vault, "set_vault_door");
	native.deactivateInteriorEntitySet(ks_casino_vault, "set_vault_door_closed");
	native.refreshInterior(ks_casino_vault);
	native.activateInteriorEntitySet(ks_casino_main, "casino_manager_default");
	native.activateInteriorEntitySet(ks_casino_main, "casino_manager_workout");
	native.refreshInterior(ks_casino_main);
	native.activateInteriorEntitySet(ks_casino_back, "casino_back_laundry_damage");
	native.refreshInterior(ks_casino_back);
	native.activateInteriorEntitySet(ks_casino_tunnel, "set_tunnel_collapse");
	native.refreshInterior(ks_casino_tunnel);
	Graffitis.Enable(getConfig("Load_Graffitis"));
	BahamaMamas.Enable(getConfig("Load_Bahamamama"));
	Ufos.Enable(getConfig("Load_Ufos"));
	redCarpet.Enable(getConfig("Load_redCarpet"));
	northYankton.Enable(getConfig("Load_northYankton"));
	heistCarrier.Enable(getConfig("Load_heistCarrier"));
	cayoPerico.Enable(getConfig("Load_cayoPerico"));
	Bunkers.Enable(getConfig("Load_Bunkers"), getConfig("Load_BunkersStyle"), getConfig("Load_BunkersTier"), getConfig("Load_BunkersSecurity"), getConfig("Load_BunkersOffice"), getConfig("Load_BunkersOfficeLocked"), getConfig("Load_BunkersLocker"), getConfig("Load_BunkersRangeLights"), getConfig("Load_BunkersRangeWall"), getConfig("Load_BunkersRangeLocked"), getConfig("Load_BunkersSchematic"));
	Gun_Yacht.Enable(getConfig("Load_Gun_Yacht"));
	Yacht.Enable(getConfig("Load_Yacht"));
	Michael.Enable(getConfig("Load_Michael"), getConfig("Load_MichaelStyle"), getConfig("Load_MichaelBed"), getConfig("Load_MichaelMoviePoster"), getConfig("Load_MichaelFameShamePoster"), getConfig("Load_MichaelPlaneTicket"), getConfig("Load_MichaelSpyGlasses"), getConfig("Load_MichaelBurgerShot"), getConfig("Load_MichaelGarage"));
	Simeon.Enable(getConfig("Load_Simeon"), getConfig("Load_SimeonStyle"), getConfig("Load_SimeonShutter"));
	Franklin.Enable(getConfig("Load_Franklin"), getConfig("Load_FranklinStyle"), getConfig("Load_FranklinGlassDoor"), getConfig("Load_FranklinProgressFlyer"), getConfig("Load_FranklinProgressTux"), getConfig("Load_FranklinProgressTshirt"), getConfig("Load_FranklinBongAndWine"));
	FranklinAunt.Enable(getConfig("Load_FranklinAunt"), getConfig("Load_FranklinAuntStyle"), getConfig("Load_FranklinAuntBandana"), getConfig("Load_FranklinAuntBag"));
	Floyd.Enable(getConfig("Load_Floyd"), getConfig("Load_FloydStyle"), getConfig("Load_FloydMrJam"));
	TrevorsTrailer.Enable(getConfig("Load_TrevorsTrailer"), getConfig("Load_TrevorsTrailerStyle"), getConfig("Load_TrevorsTrailerCopHelmet"), getConfig("Load_TrevorsTrailerBriefCase"), getConfig("Load_TrevorsTrailerMichaelStuff"));
	ZancudoGates.Enable(getConfig("Load_ZancudoGates"));
	LesterFactory.Enable(getConfig("Load_LesterFactory"), getConfig("Load_LesterFactoryBluePrint"), getConfig("Load_LesterFactoryKitBag"), getConfig("Load_LesterFactoryFireman"), getConfig("Load_LesterFactoryArmour"), getConfig("Load_LesterFactoryGasMask"), getConfig("Load_LesterFactoryAgency"));
	StripClub.Enable(getConfig("Load_StripClub"), getConfig("Load_StripClubMess"));
	Ammunations.Enable(getConfig("Load_Ammunations"), getConfig("Load_AmmunationsGunStore"), getConfig("Load_AmmunationsGunClub"));
	Nightclub.Enable(getConfig("Load_Nightclub"), getConfig("Load_NightclubStyle"), getConfig("Load_NightclubPodiumStyle"), getConfig("Load_NightclubName"), getConfig("Load_NightclubSpeaker"), getConfig("Load_NightclubSecurity"), getConfig("Load_NightclubTurnTables"), getConfig("Load_NightclubTurnTablesStyle"), getConfig("Load_NightclubLights"), getConfig("Load_NightclubBar"), getConfig("Load_NightclubBooze"), getConfig("Load_NightclubTrophy"), getConfig("Load_NightclubTrophyColor"), getConfig("Load_NightclubTrophyStyle"), getConfig("Load_NightclubDryIce"), getConfig("Load_NightClubClutter"), getConfig("Load_NightClubWorkLamps"), getConfig("Load_NightClubTruck"), getConfig("Load_NightClubLightRigsOff"), getConfig("Load_NightClubRoofLightsOff"), getConfig("Load_NightClubFloorTradLights"), getConfig("Load_NightClubChest"), getConfig("Load_NightClubVaultAmmunations"), getConfig("Load_NightClubVaultMeth"), getConfig("Load_NightClubVaultFakeID"), getConfig("Load_NightClubVaultWeed"), getConfig("Load_NightClubVaultCoke"), getConfig("Load_NightClubVaultCash"), getConfig("Load_NightClubMesaBarrier"), getConfig("Load_NightClubMesaPosters"), getConfig("Load_NightClubMissionRowBarrier"), getConfig("Load_NightClubMissionRowPosters"), getConfig("Load_NightClubStrawBerryBarrier"), getConfig("Load_NightClubStrawBerryPosters"), getConfig("Load_NightClubVineWoodWestBarrier"), getConfig("Load_NightClubVineWoodWestPosters"), getConfig("Load_NightClubCypressBarrier"), getConfig("Load_NightClubCypressPosters"), getConfig("Load_NightClubDelPerroBarrier"), getConfig("Load_NightClubDelPerroPosters"), getConfig("Load_NightClubAirPortBarrier"), getConfig("Load_NightClubAirPortPosters"), getConfig("Load_NightClubElysianBarrier"), getConfig("Load_NightClubElysianPosters"), getConfig("Load_NightClubVineWoodBarrier"), getConfig("Load_NightClubVineWoodPosters"), getConfig("Load_NightClubVespucciBarrier"), getConfig("Load_NightClubVespucciPosters"));
	BikerClubhouse1.Enable(getConfig("Load_BikerClubhouse1"), getConfig("Load_WallsStyle"), getConfig("Load_WallColor"), getConfig("Load_Furnitures"), getConfig("Load_Furniturescolor"), getConfig("Load_Decoration"), getConfig("Load_Mural"), getConfig("Load_GunLocker"), getConfig("Load_ModBooth"), getConfig("Load_Meth"), getConfig("Load_Cash"), getConfig("Load_Weed"), getConfig("Load_Coke"), getConfig("Load_Counterfeit"), getConfig("Load_Documents"));
	BikerClubhouse2.Enable(getConfig("Load_BikerClubhouse2"), getConfig("Load_BikerClubhouse2_WallsStyle"), getConfig("Load_BikerClubhouse2_WallColor"), getConfig("Load_BikerClubhouse2_LowerWallsStyle"), getConfig("Load_BikerClubhouse2_LowerWallscolor"), getConfig("Load_BikerClubhouse2_Furnitures"), getConfig("Load_BikerClubhouse2_Furniturescolor"), getConfig("Load_BikerClubhouse2_Decoration"), getConfig("Load_BikerClubhouse2_Mural"), getConfig("Load_BikerClubhouse2_GunLocker"), getConfig("Load_BikerClubhouse2_ModBooth"), getConfig("Load_BikerClubhouse2_Meth"), getConfig("Load_BikerClubhouse2_Cash"), getConfig("Load_BikerClubhouse2_Weed"), getConfig("Load_BikerClubhouse2_Coke"), getConfig("Load_BikerClubhouse2_Counterfeit"), getConfig("Load_BikerClubhouse2_Documents"));
	Counterfeit.Enable(getConfig("Load_Counterfeit"), getConfig("Load_CounterfeitPrinter"), getConfig("Load_CounterfeitSecurity"), getConfig("Load_CounterfeitDryer1"), getConfig("Load_CounterfeitDryer2"), getConfig("Load_CounterfeitDryer3"), getConfig("Load_CounterfeitDryer4"), getConfig("Load_CounterfeitCash"), getConfig("Load_CounterfeitChairs"), getConfig("Load_CounterfeitCutter"), getConfig("Load_CounterfeitFurnitures"));
	Cocaine.Enable(getConfig("Load_Cocaine"), getConfig("Load_CocaineStyle"), getConfig("Load_CocaineSecurity"), getConfig("Load_CocaineCoke1"), getConfig("Load_CocaineCoke2"), getConfig("Load_CocaineCoke3"), getConfig("Load_CocaineCoke4"), getConfig("Load_CocaineCoke5"));
	BikerDocumentForgery.Enable(getConfig("Load_BikerDocumentForgeryStyle"), getConfig("Load_BikerDocumentForgeryEquipment"), getConfig("Load_BikerDocumentForgerySecurity"),	getConfig("Load_BikerDocumentForgeryChairs"), getConfig("Load_BikerDocumentForgeryProduction"), getConfig("Load_BikerDocumentForgeryFurnitures"), getConfig("Load_BikerDocumentForgeryClutter"));
	BikerMethLab.Enable(getConfig("Load_BikerMethLab"), getConfig("Load_BikerMethLabStyle"), getConfig("Load_BikerMethLabSecurity"), getConfig("Load_BikerMethLabProduction"));
	BikerWeedFarm.Enable(getConfig("Load_BikerWeedFarm"), getConfig("Load_BikerWeedFarmStyle"), getConfig("Load_BikerWeedFarmSecurity"), getConfig("Load_BikerWeedFarmPlant1Stage"), getConfig("Load_BikerWeedFarmPlant1Light"), getConfig("Load_BikerWeedFarmPlant2Stage"), getConfig("Load_BikerWeedFarmPlant2Light"), getConfig("Load_BikerWeedFarmPlant3Stage"), getConfig("Load_BikerWeedFarmPlant3Light"), getConfig("Load_BikerWeedFarmPlant4Stage"), getConfig("Load_BikerWeedFarmPlant4Light"), getConfig("Load_BikerWeedFarmPlant5Stage"), getConfig("Load_BikerWeedFarmPlant5Light"), getConfig("Load_BikerWeedFarmPlant6Stage"), getConfig("Load_BikerWeedFarmPlant6Light"), getConfig("Load_BikerWeedFarmPlant7Stage"), getConfig("Load_BikerWeedFarmPlant7Light"), getConfig("Load_BikerWeedFarmPlant8Stage"), getConfig("Load_BikerWeedFarmPlant8Light"), getConfig("Load_BikerWeedFarmPlant9Stage"), getConfig("Load_BikerWeedFarmPlant9Light"), getConfig("Load_BikerWeedFarmProduction"), getConfig("Load_BikerWeedFarmFans"), getConfig("Load_BikerWeedFarmDrying"), getConfig("Load_BikerWeedFarmChairs"));
	DoomsdayFacility.Enable(getConfig("Load_DoomsdayFacility"), getConfig("Load_DoomsdayFacilityStyle"), getConfig("Load_DoomsdayFacilityDecal"), getConfig("Load_DoomsdayFacilityLounge"), getConfig("Load_DoomsdayFacilitySleeping"), getConfig("Load_DoomsdayFacilitySecurity"), getConfig("Load_DoomsdayFacilityCannon"), getConfig("Load_DoomsdayFacilityBedroom_Control"), getConfig("Load_DoomsdayFacilityLounge_Control"), getConfig("Load_DoomsdayFacilityParts"), getConfig("Load_DoomsdayFacilityClutterStyle"), getConfig("Load_DoomsdayFacilitycrewEmblem"), getConfig("Load_DoomsdayFacilityOutfits"), getConfig("Load_DoomsdayFacilityTrophy"), getConfig("Load_DoomsdayFacilityTrophyStyle"));
    ExecutiveApartment1.Enable(getConfig("Load_ExecutiveApartment1"), getConfig("Load_ExecutiveApartment1Style"), getConfig("Load_ExecutiveApartment1Strip"), getConfig("Load_ExecutiveApartment1Booze"), getConfig("Load_ExecutiveApartment1Smoke"));
    ExecutiveApartment2.Enable(getConfig("Load_ExecutiveApartment2"), getConfig("Load_ExecutiveApartment2Style"), getConfig("Load_ExecutiveApartment2Strip"), getConfig("Load_ExecutiveApartment2Booze"), getConfig("Load_ExecutiveApartment2Smoke"));
    ExecutiveApartment3.Enable(getConfig("Load_ExecutiveApartment3"), getConfig("Load_ExecutiveApartment3Style"), getConfig("Load_ExecutiveApartment3Strip"), getConfig("Load_ExecutiveApartment3Booze"), getConfig("Load_ExecutiveApartment3Smoke"));
    HighLifeApartment1.Enable(getConfig("Load_HighLifeApartment1"), getConfig("Load_HighLifeApartment1Strip"), getConfig("Load_HighLifeApartment1Booze"), getConfig("Load_HighLifeApartment1Smoke"));
    HighLifeApartment2.Enable(getConfig("Load_HighLifeApartment2"), getConfig("Load_HighLifeApartment2Strip"), getConfig("Load_HighLifeApartment2Booze"), getConfig("Load_HighLifeApartment2Smoke"));
    HighLifeApartment3.Enable(getConfig("Load_HighLifeApartment3"), getConfig("Load_HighLifeApartment3Strip"), getConfig("Load_HighLifeApartment3Booze"), getConfig("Load_HighLifeApartment3Smoke"));
    HighLifeApartment4.Enable(getConfig("Load_HighLifeApartment4"), getConfig("Load_HighLifeApartment4Strip"), getConfig("Load_HighLifeApartment4Booze"), getConfig("Load_HighLifeApartment4Smoke"));
    HighLifeApartment5.Enable(getConfig("Load_HighLifeApartment5"), getConfig("Load_HighLifeApartment5Strip"), getConfig("Load_HighLifeApartment5Booze"), getConfig("Load_HighLifeApartment5Smoke"));
    HighLifeApartment6.Enable(getConfig("Load_HighLifeApartment6"), getConfig("Load_HighLifeApartment6Strip"), getConfig("Load_HighLifeApartment6Booze"), getConfig("Load_HighLifeApartment6Smoke"));
    HighEndApartment1.Enable(getConfig("Load_HighEndApartment1"), getConfig("Load_HighEndApartment1Strip"), getConfig("Load_HighEndApartment1Booze"), getConfig("Load_HighEndApartment1Smoke"));
    HighEndApartment2.Enable(getConfig("Load_HighEndApartment2"), getConfig("Load_HighEndApartment2Strip"), getConfig("Load_HighEndApartment2Booze"), getConfig("Load_HighEndApartment2Smoke"));
    LowEndHouse.Enable(getConfig("Load_LowEndHouse"), getConfig("Load_LowEndHouseStrip"), getConfig("Load_LowEndHouseBooze"), getConfig("Load_LowEndHouseSmoke"));
    MidEndHouse.Enable(getConfig("Load_MidEndHouse"), getConfig("Load_MidEndHouseStrip"), getConfig("Load_MidEndHouseBooze"), getConfig("Load_MidEndHouseSmoke"));
    HighEndHouse1.Enable(getConfig("Load_HighEndHouse1"), getConfig("Load_HighEndHouse1Strip"), getConfig("Load_HighEndHouse1Booze"), getConfig("Load_HighEndHouse1Smoke"));
    HighEndHouse2.Enable(getConfig("Load_HighEndHouse2"), getConfig("Load_HighEndHouse2Strip"), getConfig("Load_HighEndHouse2Booze"), getConfig("Load_HighEndHouse2Smoke"));
    HighEndHouse3.Enable(getConfig("Load_HighEndHouse3"), getConfig("Load_HighEndHouse3Strip"), getConfig("Load_HighEndHouse3Booze"), getConfig("Load_HighEndHouse3Smoke"));
    HighEndHouse4.Enable(getConfig("Load_HighEndHouse4"), getConfig("Load_HighEndHouse4Strip"), getConfig("Load_HighEndHouse4Booze"), getConfig("Load_HighEndHouse4Smoke"));
    HighEndHouse5.Enable(getConfig("Load_HighEndHouse5"), getConfig("Load_HighEndHouse5Strip"), getConfig("Load_HighEndHouse5Booze"), getConfig("Load_HighEndHouse5Smoke"));
    HighEndHouse6.Enable(getConfig("Load_HighEndHouse6"), getConfig("Load_HighEndHouse6Strip"), getConfig("Load_HighEndHouse6Booze"), getConfig("Load_HighEndHouse6Smoke"));
    HighEndHouse7.Enable(getConfig("Load_HighEndHouse7"), getConfig("Load_HighEndHouse7Strip"), getConfig("Load_HighEndHouse7Booze"), getConfig("Load_HighEndHouse7Smoke"));
    HighEndHouse8.Enable(getConfig("Load_HighEndHouse8"), getConfig("Load_HighEndHouse8Strip"), getConfig("Load_HighEndHouse8Booze"), getConfig("Load_HighEndHouse8Smoke"));
alt.on("connectionComplete", () => {
	if(getConfig("Load_cayoPerico")){
		const blip = new alt.PointBlip(5943.5679611650485, -6272.114833599767, 2);
		blip.alpha = 0;
		alt.everyTick(() => {
			native.setRadarAsExteriorThisFrame();
			native.setRadarAsInteriorThisFrame(alt.hash("h4_fake_islandx"), 4700.0, -5145.0, 0, 0);
			native.setDeepOceanScaler(0.1);
		});
	}
});