import { EnableIpl } from 'mr-functions';
export let northYankton = {
    ipl : [
        "prologue01",
        "prologue01c",
        "prologue01d",
        "prologue01e",
        "prologue01f",
        "prologue01g",
        "prologue01h",
        "prologue01i",
        "prologue01j",
        "prologue01k",
        "prologue01z",
        "prologue02",
        "prologue03",
        "prologue03b",
        "prologue03_grv_dug",
        "prologue_grv_torch",
        "prologue04",
        "prologue04b",
        "prologue04_cover",
        "des_protree_end",
        "des_protree_start",
        "prologue05",
        "prologue05b",
        "prologue06",
        "prologue06b",
        "prologue06_int",
        "prologue06_pannel",
        "plg_occl_00",
        "prologue_occl",
        "prologuerd",
        "prologuerdb"],
        Enable : function(state){ EnableIpl(northYankton.ipl, state) }
}